### ISSUE TITLE
Excess text in Conformance Claims section

### ISSUE THREAD

**Issue by kbeiii** [commoncriteria/tls#16]
In the second paragraph of section 2 (Conformance Claims; https://commoncriteria.github.io/pp/tls/tls-release.html#ajq_32) the sentence that includes the bulleted list is not necessary and should be removed.  Conformance to packages is defined by the CC and there's really no provision for the package to say what needs to happen for a particular conformance claim; that's done at the PP/PP-Module/ST level.

**Comment by jeffblank** [comment]
Okay.  I've removed it (well, commented it out) per https://github.com/commoncriteria/tls/commit/04ec63dcebd29d95fb08216be431a72a185ce585

Instead, we should probably move the text from the introductions of the Appendices which explains what (1) selection-based (2) objective and (3) optional actually mean to some kind of introductory section.   (And this was just revised per your other comment.)  If not Conformance Claims, then somewhere else in the introductory text.  That is more logical than just having the first Appendix explains why it (and the others) exist.  It will also help the reader understand the format earlier. 

I don't want to close this ticket until we can sort that out.  This will also dramatically simplify things going forward.

**Comment by kbeiii** [comment]
Agree with that approach; and also that it will give us some good boilerplate for future packages.

**Comment by jeffblank** [comment]
I've done this here: https://commoncriteria.github.io/pp/tls/tls-release.html#docformat While not perfect, it's probably suitable as prototypical boilerplate for future Packages.  And with some modification, suitable for PPs and PP-Modules as well.
