### ISSUE TITLE
Add "Short Name" for package

### ISSUE THREAD

**Issue by kbeiii** [commoncriteria/tls#17]
While not currently required by CC3.1r5, the updated package definition in the ISO version is going to require a short name (like "EAL3").  It'd be good to add this so we have it, and can make it easy to reference in our PPs and PP-Modules.

I'd just recommend inserting in the Introduction (maybe around here: https://commoncriteria.github.io/pp/tls/tls-release.html#ajq_1) something like:

This "Functional Package for Transport Layer Security" (short name "TLS-PKG") defines functional requirements for the implementation of the Transport Layer Security (TLS) and  Datagram TLS (DTLS) protocols.

**Comment by jeffblank** [comment]
Done -- added here: https://github.com/commoncriteria/tls/commit/e7d1fba759f04dcd047829dfef499299dc287714
