### ISSUE TITLE
Slight rewording for "Baseline Requirement" language in appendices

### ISSUE THREAD

**Issue by kbeiii** [commoncriteria/tls#18]
Appendices A and B use language like "Baseline requirements which must be performed by the product are contained in the main body of this Package in 3 Security Requirements and in the base PPs or PP-Modules which use this Package."  (https://commoncriteria.github.io/pp/tls/tls-release.html#ajq_52 and https://commoncriteria.github.io/pp/tls/tls-release.html#ajq_59)  The issue is that I think a PP or PP-Module could make the requirements optional, and so saying that the baseline requirements must be performed by the product would be inaccurate.  Plus, since this is a package, I just in general don't like talking about products as the "customers" of the package; in my mind it's really just PPs and PP-Modules (and STs, be we don't care about these in the exact conformance case).

So, I'd recommend replacing the language with something like the following.  For Appendix A, replace the first paragraph with:

"Baseline requirements which must be included in the PP/PP-Module/ST
that claims conformance to this package are contained in <link 3
Security Requirements>. There are three other types of requirements
that can be included in a PP/PP-Module/ST claiming conformance to this
package.  The first type (in this Appendix) are requirements that can
can be included in the PP/PP-Module/ST, but inclusion is at the
discretion of the PP/PP-Module/ST author. The second type (in <link
Appendix B - Selection-Based Requirements>) are requirements based on
selections in the requirements in <link 3 Security Requirements>: if
certain selections are allowed/made in the PP/PP-Module/ST, then the
corresponding requirements in that appendix must be included.  The
third type (in <link Appendix C - Objective Requirements>) are
optional reqiurements that will be included in the baseline
requirements in future versions of this package, so adoption by
vnedors is encouraged.  Otherwise, they are treated the same as
Optional Requirements."

For Appendix B, recommend replacing the first paragraph with the following:

"As indicated in <link Appendix A>, requirements that must be included
in the PP/PP-Module/ST claiming conformance to this package are listed
in <link 3 Security Requirements>. For requirements that have
selections, if the PP/PP-Module allows the selection (or the ST
selects particular selections), then there are additional requirements
based on these selections contained in this appendix that will need to
be included in the PP/PP-Module/ST."

**Comment by jeffblank** [comment]
Addressed this in commit:
https://github.com/commoncriteria/tls/commit/5de14ae8f4995a8e23d82b1aa227dce071a86d2d
