### ISSUE TITLE
Visual diff against 1.1 is missing

### ISSUE THREAD

**Issue by adelton** [commoncriteria/tls#39]
The https://github.com/commoncriteria/tls/blob/master/README.md has a link  [Visual Diff against 1.1](https://commoncriteria.github.io/tls/diff-v1.1.html)(html) but following the link yields

> 404 File not found

Please provide a valid diff between the 1.1 and 2.0 versions of the Functional Package.

**Comment by adelton** [comment]
There are now links https://commoncriteria.github.io/tls/master/diff-v1.1.html and https://commoncriteria.github.io/tls/release-2.0/diff-v1.1.html in those new tables at the top of the README, but they are empty.

**Comment by kgal** [comment]
Should be fixed (Really diffs should be done against release branches and not tags).

**Comment by adelton** [comment]
I confirm that https://commoncriteria.github.io/tls/release-2.0/diff-release-1.1.html works. Thank you.
