### ISSUE TITLE
TLS1.2 as a selection in FCS_TLSS_EXT.1.2 

### ISSUE THREAD

**Issue by dlmo** [commoncriteria/tls#4]
Since FCS_TLS_EXT.1.1 requires TLS1.2, it seems inconsistent for FCS_TLSS_EXT.1.2 to have a selection to deny TLS1.2 connections

**Comment by jeffblank** [comment]
Indeed.  Updated to reflect. https://commoncriteria.github.io/pp/tls/tls.html#FCS_TLSS_EXT.1.2
