### ISSUE TITLE
Test#5 for ciphersuites requirements

### ISSUE THREAD

**Issue by dlmo** [commoncriteria/tls#7]
Assurance Activity Test #5 for FCS_TLSC_EXT.1.1 and FCS_TLSS_EXT.1.1 isn't actually testing anything about the ciphersuites themselves -- should this assurance activity be moved to a different pair of requirements?

**Comment by jeffblank** [comment]
We added in TLS version selections to the same element, which one of these tests covers.  The other tests regard general TLS behavior (which we can consider in scope).
